const catchError = (error)=>{
    return{
        type:'MANU_ERROR'
    }
}

export {
    catchError
};